# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KfPblxeielK4UpbVclednr4BD16XQF2F
"""

!pip install experta

!pip install --upgrade frozendict

from experta import *

class Diagnosis(KnowledgeEngine):

    @Rule(Fact(cough=True) & Fact(fever=True) & Fact(fatigue=True))
    def flu(self):
        print("Diagnosis: You may have the Flu.")

    @Rule(Fact(cough=True) & Fact(fever=True) & Fact(breathing_difficulty=True))
    def pneumonia(self):
        print("Diagnosis: You may have Pneumonia.")

    @Rule(Fact(sneezing=True) & Fact(runny_nose=True) & Fact(cough=False))
    def cold(self):
        print("Diagnosis: You may have a Common Cold.")

    @Rule(Fact(sore_throat=True) & Fact(fever=True))
    def throat_infection(self):
        print("Diagnosis: You may have a Throat Infection.")

    @Rule(Fact(cough=False) & Fact(fever=False) & Fact(fatigue=False))
    def healthy(self):
        print("Diagnosis: You Seem To Be Healthy.")

    @Rule(Fact(fever=True) & Fact(cough=True) & Fact(loss_of_smell=True))
    def covid(self):
        print("Diagnosis: You may have COVID-19.")

    @Rule(Fact(sneezing=True) & Fact(itchy_eyes=True) & Fact(runny_nose=True))
    def allergy(self):
        print("Diagnosis: You may have an Allergy.")

    @Rule(Fact(wheezing=True) & Fact(chest_tightness=True) & Fact(breathing_difficulty=True))
    def asthma(self):
        print("Diagnosis: You may have Asthma.")

    @Rule(Fact(headache=True) & Fact(nausea=True) & Fact(light_sensitivity=True))
    def migraine(self):
        print("Diagnosis: You may have a Migraine.")

def get_input():
    """Helper function to get user input as boolean (yes/no)."""
    def ask_question(question):
        return input(question + " (yes/no): ").strip().lower() == "yes"

    return {
        "cough": ask_question("Do you have a cough?"),
        "fever": ask_question("Do you have a fever?"),
        "fatigue": ask_question("Do you feel fatigued?"),
        "breathing_difficulty": ask_question("Do you have breathing difficulty?"),
        "sneezing": ask_question("Are you sneezing?"),
        "runny_nose": ask_question("Do you have a runny nose?"),
        "sore_throat": ask_question("Do you have a sore throat?"),
        "loss_of_smell": ask_question("Have you lost your sense of smell?"),
        "itchy_eyes": ask_question("Do you have itchy eyes?"),
        "wheezing": ask_question("Are you wheezing?"),
        "chest_tightness": ask_question("Do you feel chest tightness?"),
        "headache": ask_question("Do you have a headache?"),
        "nausea": ask_question("Do you feel nauseous?"),
        "light_sensitivity": ask_question("Are you sensitive to light?")
    }

# Running the Expert system
if __name__ == "__main__":
    symptoms = get_input()
    engine = Diagnosis()
    engine.reset()

    for symptom, present in symptoms.items():
        engine.declare(Fact(**{symptom: present}))

    engine.run()